# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ca2fdead3928301d94677e5ac3f7026387eb0cee33574ba7d321c69c9fb7cf296a6cdce7403a9324ef8d6c9a42eb975ade6f995e6f142584c325232de923df0

test:
  secret_key_base: 6272a33dff325af2153a784f137d5ab4d266c3ceaa4fa9faac5c9faee401713dbb3a87772f20161cd221a2bc76276c9eff98fa3c86a7b4c343d0aa9847c1c395

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
